language: objective-c
os: osx
osx_image: xcode10.1

xcode_project: RxPullToRefresh.xcodeproj
xcode_scheme: RxPullToRefresh

branches:
  only:
    - master
    - develop
#    - "/^v?[0-9\\.]+/"

cache:
  directories:
    - Pods
    - Carthage

env:
  global:
    - secure: IsSPmEYizg0SVZoWqO8JnSgCKlNSBLIFs+XZjOCjb12Z+YToMS3tmo+EYrmaKNJRMrvJEFyRlgyxlyEQGHc57eFGzZAjLGsiiIu++xY7AzDALC+CDG3w2daNF+pWXX58145Wj5CpOrkauF+DHUMYCQWa3g4JGoMmP001fjKlF+9TUF7K017Ae6awVu3YFJqvO2KuCEpe3J7b6Ii0hjUEnHMzHgK+ZFwGbc8QXz21AGO5YXT3+6zxaLB4TdEyazRC/QxaDBpmSE8k4RMeOXBTbwhpJhWbrDuGGJWw46yO006d7YdU8+fkf6hSBswN5YGbOga8dwRB4vVilJ6P8iiUV9QL4C1BxU8jFBkil563o5mbl6MZrEjXPQuvwyB9xSf6LGjYyVXrAVj6nIar+QcfwSIqn2520qYxrYo5CAaZ/9ozmRg4v4fbnA6m2fEW1lI7USQGKcByit6ZGxQQ6YwdS0mw83fvGotxptgc/by2e7b1O64i2BWEh/5fHt/B3+6j7HkzDHvMKoOgFoNKMbrtEit9R7Dnrdsgd0awVnQzY0EdWdmYGH1A9h9pHJhmEoQq2S1X2tOf1WC0y67dY1FIMMk+27dn7ZBTsmKKdQf/RCYNSxhzHFjyaMr5nBkqxf4UV73l0JMT6Nhi5KrSCIYnOUA9peEETXmo9oBssPuVHSk=

matrix:
  include:
#    - env: CARTHAGE_TEST="YES"
#    - env: POD_LINT="YES"
#    - env: SWIFT_LINT="YES"

#    - env: XCODE_TEST="YES" DEST="platform=iOS Simulator,OS=12.1,name=iPhone XS Max" COVERAGE="YES" CODECOV_FLAG="ios12"
#    - env: XCODE_TEST="YES" DEST="platform=iOS Simulator,OS=11.4,name=iPhone 7 Plus"
#    - env: XCODE_TEST="YES" DEST="platform=iOS Simulator,OS=10.3.1,name=iPhone 6"
#    - env: XCODE_TEST="YES" DEST="platform=iOS Simulator,OS=9.3,name=iPhone 5s"

    - env: XCODE_TEST="YES" RUNTIME="iOS 12.1"   DEVICE="iPhone XS Max" COVERAGE="YES" CODECOV_FLAG="ios12"
    - env: XCODE_TEST="YES" RUNTIME="iOS 11.4"   DEVICE="iPhone X"
    - env: XCODE_TEST="YES" RUNTIME="iOS 10.3.1" DEVICE="iPhone 7 Plus"
    - env: XCODE_TEST="YES" RUNTIME="iOS 9.3"    DEVICE="iPhone 6s"

before_install:
  - if [ "$POD_LINT" == "YES" ]; then
    gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet;
    fi
  - if [ "$CARTHAGE_TEST" = "YES" ] || [ "$XCODE_TEST" = "YES" ]; then
    gem install xcpretty -N --no-ri --no-rdoc --quiet;
    brew update --quiet;
    brew outdated carthage || brew upgrade carthage --quiet;
    fi
  - if [ "$CARTHAGE_TEST" = "YES" ] || [ "$XCODE_TEST" = "YES" ]; then
    carthage bootstrap --platform iOS --no-use-binaries --cache-builds;
    fi
#  - swift -version;
#  - xcrun simctl list;
#  - xcodebuild -version;
#  - xcodebuild -showsdks;
#  - xcodebuild -list;

install:
  - if [ "$SWIFT_LINT" == "YES" ]; then
    ./install-swiftlint.sh;
    fi

before_script:
  - DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g");
  - RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g");
  - DESTINATION_ID=$(xcrun simctl create Travis $DEVICE_ID $RUNTIME_ID);
  - xcrun simctl boot $DESTINATION_ID;

script:
  - set -o pipefail;
  - if [ "$XCODE_TEST" == "YES" ]; then
#    xcodebuild clean test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$DEST" -enableCodeCoverage $COVERAGE | xcpretty -c;
    xcodebuild clean build-for-testing test-without-building -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "id=$DESTINATION_ID" | xcpretty -c;
    fi
  - if [ "$CARTHAGE_TEST" == "YES" ]; then
    carthage build --no-skip-current --platform iOS;
    fi
  - if [ "$POD_LINT" == "YES" ]; then
    pod repo update;
    pod lib lint;
    fi
  - if [ "$SWIFT_LINT" == "YES" ]; then
    swiftlint lint;
    fi

after_success:
  - if [ "$COVERAGE" == "YES" ]; then
    bash <(curl -s https://codecov.io/bash) -J 'RxPullToRefresh' -cF "$CODECOV_FLAG" -y ".codecov.yml";
    fi

after_failure:
  - if [ "$CARTHAGE_TEST" == "YES" ]; then
    cat $TMPDIR/carthage-*.log | true
    cat /var/log/system.log
    fi
  - if [ "$XCODE_TEST" == "YES" ]; then
    find $HOME/Library/Developer/Xcode/DerivedData/RxPullToRefresh-*/Logs/ -name '*.log' -print0 | xargs -0 cat
    cat /var/log/system.log
    fi

notifications:
  email: false
